### ISSUE TITLE
Decrease number of transactions when adding and withdrawing stCELO

### ISSUE THREAD

**Issue by product-matt** [celo-org/staked-celo#86]

**Comment by soloseng** [comment]
Upon further investigation, decreasing the number of transactions submitted when activating/voting or withdrawing will require changes to the `account.withdraw()`, where a list of: `group`, `lesserAfterPendingRevoke`, `greaterAfterPendingRevoke`, `lesserAfterActiveRevoke`, `greaterAfterActiveRevoke`, `index`

need to be included in order to unlock the total revoke amount of all groups fro that beneficiary.

**Comment by product-matt** [comment]
resolved with StakedCelo v2
